### PR TITLE
fix: add bg color to saved chart images

### LINKED ISSUE #37: Charts - Light mode - when downloaded as PNG/JPG, the text color is barely visible
**Before submitting a bug:**

- [ yes] Is this reproducible in the latest version of Shidoka?
- [ yes] Is this reproducible in the [Shidoka Storybook](https://shidoka-applications.netlify.app)?
- [ ] Is this reproducible in a [Sandbox](https://codesandbox.io)?
- If it's not reproducible in any of the above scenarios, please do not open a bug report as it is an application-level issue.

**Describe the bug**

When chart is downloaded as PNG or JPG, the text color in the image is not same as UI

**To Reproduce**

1. Open Shidoka charts application
2. Navigate to any chart
3. click on download button
4. Download as PNG or JPG
5. Observe

**Expected behavior**

The text color must be same as UI

**Screenshots**

Image
Image

**Environment**

**Additional context**

[AB#2199527](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2199527)

### PR DESCRIPTION
**Pull request by brian-patrick-3**
## Summary

Adds a BG color to the canvas when triggering an image download, then removes it after.

## ADO Story or GitHub Issue Link

resolves #37

### CODE REVIEW

**Review by jaideep08 — APPROVED** [review]

**Comment by kumarivijeta** [comment]
Observation:

1. In Light and Dark mode.
 -On click of download png/jpeg , the original chart color's changes .
 - In Light Mode , download png/jpeg should be respective theme.


https://github.com/user-attachments/assets/9328308e-473a-490e-b700-ee92fb137e7d

File: src/components/chart/chart.ts [hunk 1]
```diff
@@ -820,15 +820,30 @@ export class KDChart extends LitElement {
   private handleDownloadImage(e: Event, jpeg: boolean) {
     e.preventDefault();
 
+    // add bg color to canvas
+    const context: any = this.canvas.getContext('2d');
+    const color = getComputedStyle(document.documentElement).getPropertyValue(
+      '--kd-color-background-page-default'
```
Comment (kumarivijeta) [inline src/components/chart/chart.ts:826]: Instead of `getComputedStyle()` , `getTokenThemeVal('--kd-color-background-page-default')`; would be more precise fix here which will resolve respective theme download files and changing original chart color issue.

**Review by kumarivijeta — APPROVED** [review]

File: src/components/chart/chart.ts (hunk 1 above)
Comment (kumarivijeta) [reply src/components/chart/chart.ts]: One more thing I have noticed in Safari , On click of download icon, options are not showing up.

Comment (brian-patrick-3) [reply src/components/chart/chart.ts]: Hmm seems like Safari is not activating :focus-within for some reason. Might have to add a prop to control it on click.

Comment (kumarivijeta) [reply src/components/chart/chart.ts]: adding `tabindex="0"` shows up option in Safari.

image

Comment (kumarivijeta) [reply src/components/chart/chart.ts]: On Safari , applications also having the same issue.

**Review by srpriyankashetty — APPROVED** [review]
Verified and looks fine
image

File: src/components/chart/chart.ts (hunk 1 above)
Comment (brian-patrick-3) [reply src/components/chart/chart.ts]: Nice find. Would you mind pushing those fixes?

Comment (kumarivijeta) [reply src/components/chart/chart.ts]: Yes, will fix it. For tracking purpose , I will create a bug and list down the component's having focus issue.

Comment (brian-patrick-3) [reply src/components/chart/chart.ts]: Thanks, easier that way since I'm on Windows and have to use BrowserStack to test Mac browsers.
